circlrciの設定

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -18,15 +18,15 @@ jobs:
             sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
             sudo chmod +x /usr/local/bin/docker-compose
       - run:
-          name: Check if default.conf exists
+          name: Check if default.conf exists and its permissions
           command: |
-            echo "Checking for default.conf in the host:"
-            ls -la /home/circleci/project/docker/nginx/default.conf || echo "default.conf not found"
+            echo "Checking for default.conf and its permissions on CircleCI:"
+            ls -la ./docker/nginx/default.conf || echo "default.conf not found"
       - run:
           name: Start Docker Compose
           command: docker compose up -d --build
       - run:
-          name: Verify nginx config file exists in container
+          name: Verify nginx config file exists in container and check permissions
           command: docker compose exec nginx ls -la /etc/nginx/conf.d/
       - run:
           name: List files in /var/www/ inside the container
